### ISSUE TITLE
[Feature request] tile size dividible by 8

### ISSUE THREAD

**Issue by fractal-fumbler** [ssitu/ComfyUI_UltimateSDUpscale#1]
Hello :)
thanks a lot for your work :+1: 

since ComfyUI now supports steps count = 8. Is it possible to make tile_width and tile_height same step count = 8?

**Comment by ssitu** [comment]
Does 02c17d562daf71d357fca83e6e95fb432c48bccb fix it for you?

**Comment by ssitu** [comment]
I will consider this fixed.

**Comment by fractal-fumbler** [comment]
hello :) was a lot of work recently :)

yup tile height and width are working, thanks a lot!
