### ISSUE TITLE
Erro after latest update

### ISSUE THREAD

**Issue by manny5457** [ssitu/ComfyUI_UltimateSDUpscale#11]
hi, USDUpscaler was working perfectly, this morning updated to latest version of node and now get this error "UltimateSDUpscale:     - Required input is missing: force_uniform_tiles". I am trying to upscale using controlnet tile, as I said it was working fine, but after the update the Ultimate SDupscale node gives me this error. Any help in resolving this would be apreciated. Thanks.

**Comment by ssitu** [comment]
> hi, USDUpscaler was working perfectly, this morning updated to latest version of node and now get this error "UltimateSDUpscale: - Required input is missing: force_uniform_tiles". I am trying to upscale using controlnet tile, as I said it was working fine, but after the update the Ultimate SDupscale node gives me this error. Any help in resolving this would be apreciated. Thanks.

I added a new setting to the node recently. I believe the new widget will appear if you refresh the UI after loading your workflow. If not, you should replace the old node with a newly created one.

**Comment by manny5457** [comment]
thank you, resolved.
