### ISSUE TITLE
Cannot upscale with ControlNet+MultiAreaConditioning

### ISSUE THREAD

**Issue by andreszs** [ssitu/ComfyUI_UltimateSDUpscale#13]
Whenever I try to upscale a 768x768 image created with [MultiAreaConditioning](https://github.com/Davemane42/ComfyUI_Dave_CustomNode), the result is a tiled mix of partial images as shown:

![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/10298071/1a5cd2f2-a607-4e82-883b-f7f150a15aeb)

Using `tile_width` and `tile_height `of 768 instead of 512 also results in a wrong image:

![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/10298071/3e704d81-f958-4ed2-b239-8ef60c0a43d6)

I have no idea on how to configure the plugin because the README says nothing about the node's settings. Any help will be appreciated, thank.

**Comment by ssitu** [comment]
The denoise is too high. It is recommended to keep it below 0.4 denoise. If you want to keep the 1.0 denoise then you can add ControlNet tile to keep the composition of the image. You can find details about the node settings here: https://github.com/ssitu/ComfyUI_UltimateSDUpscale#usage
