### ISSUE TITLE
it is slower than a1111 webui

### ISSUE THREAD

**Issue by whmc76** [ssitu/ComfyUI_UltimateSDUpscale#14]
It seems that the highres fix in comfyui is to enlarge the tiles one by one in sequence, and webui is processed at the same time.
Can you improve this a little bit, it will be perfect

**Comment by ssitu** [comment]
I don't quite understand, could you clarify what you mean some more?

**Comment by andreszs** [comment]
I'm not sure what he means but indeed the Ultimate SD Upscale node takes an absurd amount of time. For a simple 2x upscale from 768x768, the node's progress repeats itself at least a dozen times without reason. Creating the original image takes 40 seconds, but the 2x upscaling takes around 5 minutes with a GTX 1660 6GB card. Is there a recommended setting for tile_width or tile_height to improve speed?

In auto1111 upscaling by 2x takes mathematically 4x longer than the original image's generation speed, here it's 10x slower somehow.

**Comment by ssitu** [comment]
> I'm not sure what he means but indeed the Ultimate SD Upscale node takes an absurd amount of time. For a simple 2x upscale from 768x768, the node's progress repeats itself at least a dozen times without reason. Creating the original image takes 40 seconds, but the 2x upscaling takes around 5 minutes with a GTX 1660 6GB card. Is there a recommended setting for tile_width or tile_height to improve speed?
> 
> In auto1111 upscaling by 2x takes mathematically 4x longer than the original image's generation speed, here it's 10x slower somehow.

So you are upscaling 2x with a tile size of 768x768 and it does more than 4 tiles? Did you have seam fix on?

**Comment by andreszs** [comment]
Yes, the node executed itself 8 times and took 15 minutes, is this normal or there's something wrong? Here's the cmd output and the full workflow.

## CMD
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/10298071/a7126ccb-6fe5-42a5-a5e2-83da35995fd8)

## Workflow
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/10298071/6a65dd93-1542-40b0-af95-880e75a42d1e)

Also, with these settings the results were not much better than the regular upscaler node that takes 10 seconds. The eyes were better but the overall image was slightly more blurry.

**Comment by ssitu** [comment]
So it says that you have seam fix set to HALF_TILE. If you set that to NONE, it will only do 4 tiles instead of 8. This is the same behavior as in A1111. I’m not sure about the blurriness, if it happens with the original extension in A1111 then it’s a problem with the method than my port of it over to ComfyUI. I’ve seen some people use a different, more generic prompt for the upscale rather than reuse the prompt they use to generate the base image, so you can give that a try.

**Comment by andreszs** [comment]
The problem is that if I don't enable HALF_TILE seam fix, the result is a wrong image as explained in #13 . is there some solution to prevent using the slower seam fix?

**Comment by ssitu** [comment]
Try lowering the denoise value to something like 0.1

If it still shows seams when it is near 0, then there is something wrong.

**Comment by ronaldomirandah** [comment]
I am giving up on this node, its completely SLLLOOWWWWW
