### ISSUE TITLE
node will not load in pre-made workflow

### ISSUE THREAD

**Issue by Psokratease** [ssitu/ComfyUI_UltimateSDUpscale#17]
Hi, I'm using Comfyui on windows 11. I get the following error:
 "When loading the graph, the following node types were not found:
UltimateSDUpscale
Nodes that have failed to load will show as red on the graph."

I have this installed. When I pull up manager to install missing nodes it shows it installed already.  I have deleted it, installed directly thru git, and git pull, reinstalled everything half a dozen times. I cannot get it to work.  Please know I'm fairly new to this and do not know programming. However, I was able to install all the other nodes, so far, with no difficulty. Please tell me what step I am missing!
If it makes a difference, the workflow I am trying to load is:  sdxl10COMFYCONFIG_v10
Thanks

**Comment by ssitu** [comment]
Are you able to create the node yourself? Also I don't know this workflow, where is it from or are you able to share it?

**Comment by Psokratease** [comment]
The workflow I downloaded from Civitai: https://civitai.com/models/122046?modelVersionId=132844
I haven't tried to make it myself , I am trying to learn Comfyui by examining the workflow. I know wiring and electricity and the "schematics" of the node system interest me.  I am very new.   
I did download other workflows that utilized nodes I did not have, and I simply installed them via the manager. Now the others work, but just not this one. Perhaps the workflow is flawed in some way? I don't know.

**Comment by ssitu** [comment]
The workflow loads fine for me, is there an error that appears in your console/terminal?

**Comment by Psokratease** [comment]
When you look at this please remember I am new...I'm sure I have many nodes I don't need (I downloaded them to try and make the workflows load up) Probably some here I don't need, but I don't know which. Here is the entire output and I appreciate you're patience:

D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-08-15 16:48:12.229583

Prestartup times for custom nodes:
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65462 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V3.16.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2)
### Loading: ComfyUI-Manager (V0.22.3)
### ComfyUI Revision: 1290 [a2ce9655]
### ComfyUI-Manager: Copy .js from 'D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\js\comfyui-manager.js' to 'D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\web\extensions\comfyui-manager'
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\__init__.py", line 3, in <module>
    from .sample import KSamplerSetting, KSamplerOverrided, KSamplerXYZ
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\sample.py", line 11, in <module>
    from .model import merge2
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\merge2.py", line 8, in <module>
    from comfy.ldm.models.diffusion.ddpm import LatentDiffusion
ModuleNotFoundError: No module named 'comfy.ldm.models.diffusion.ddpm'

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: No module named 'comfy.ldm.models.diffusion.ddpm'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
### Loading: Save img prompt
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\com\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyuiExtremeDetail_v10\\__init__.py'

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiExtremeDetail_v10 module for custom nodes: [Errno 2] No such file or directory: 'D:\\com\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyuiExtremeDetail_v10\\__init__.py'
Comfyroll Custom Nodes: Loaded
__name__ : ComfyUI_node_Lilly
__file__ : D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable
─────────────────────────────────────────────────────  init start  ─────────────────────────────────────────────────────
__name__ : custom_nodes.ComfyUI_node_Lilly
__file__ : D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable
[16:48:28] Load ok   : CheckpointLoaderRandom                                                             __init__.py:83
[16:48:28] os.path.basename(__file__) :  mypath.py                                                          mypath.py:29
           os.path.abspath(__file__)  :                                                                     mypath.py:32
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_node
           s\ComfyUI_node_Lilly\mypath.py
           os.path.abspath(__file__)  :                                                                     mypath.py:35
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_node
           s\ComfyUI_node_Lilly\mypath.py
           os.path.normpath(__file__) :                                                                     mypath.py:38
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_node
           s\ComfyUI_node_Lilly\mypath.py
           os.path.dirname(normpath) :                                                                      mypath.py:41
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_node
           s\ComfyUI_node_Lilly
           os.path.basename(normpath) : mypath.py                                                           mypath.py:44
           os.path.abspath(sys.modules['__main__'].__file__) :                                              mypath.py:47
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\main.py
           os.path.dirname(mainFile) :                                                                      mypath.py:49
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI
           Load ok   : CheckpointLoaderSimpleText                                                         __init__.py:83
           wildcards card_path :                                                                         wildcards.py:36
           D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_n
           odes\ComfyUI_node_Lilly\..\..\wildcards\**\*.txt
           cards file count :  0                                                                        wildcards.py:187
           wildcards test : aest                                                                        wildcards.py:218
           wildcards test : *test                                                                       wildcards.py:219
           wildcards test : ?est                                                                        wildcards.py:220
           wildcards test : test                                                                        wildcards.py:221
           wildcards test : /test                                                                       wildcards.py:222
           wildcards test : /0/test                                                                     wildcards.py:223
           Load ok   : CLIPTextEncodeWildcards                                                            __init__.py:83
           Load ok   : LoraLoaderText                                                                     __init__.py:83
           Load ok   : LoraLoaderTextRandom                                                               __init__.py:83
           Load ok   : Random_Sampler                                                                     __init__.py:83
           Load ok   : VAELoaderDecode                                                                    __init__.py:83
           Load ok   : VAELoaderText                                                                      __init__.py:83
Total VRAM 24576 MB, total RAM 65462 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
           Load ok   : SimpleSampler                                                                      __init__.py:83
           Load ok   : SaveImageSimple                                                                    __init__.py:83
           Load ok   : TextWildcards                                                                      __init__.py:83
──────────────────────────────────────────────────────  init end  ──────────────────────────────────────────────────────
Using xformers cross attention
Warning: Stable Diffusion not found at path D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ldm
Warning: Taming Transformers not found at path D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\taming-transformers\taming
Warning: CodeFormer not found at path D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\CodeFormer\inference_codeformer.py
Warning: BLIP not found at path D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\BLIP\models\blip.py
Warning: k_diffusion not found at path D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\k-diffusion\k_diffusion\sampling.py
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\__init__.py", line 6, in <module>
    from .modules import deepbooru
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\deepbooru.py", line 10, in <module>
    from . import paths, deepbooru_model, devices, shared, images
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\shared.py", line 9, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger module for custom nodes: No module named 'gradio'
[tinyterraNodes] Loaded
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories/ultimate_sd_upscale/scripts/ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 5, in <module>
    from utils import pil_to_tensor, tensor_to_pil, get_crop_region, expand_crop, crop_cond
ImportError: cannot import name 'pil_to_tensor' from 'utils' (D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\utils.py)

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'pil_to_tensor' from 'utils' (D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\utils.py)
!! Trying to start the node
D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions-main\extensions
D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\web\extensions\failfast-comfyui-extensions
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_generator.py", line 3, in <module>
    from preprocess import preprocess
ModuleNotFoundError: No module named 'preprocess'

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_generator.py module for custom nodes: No module named 'preprocess'
Traceback (most recent call last):
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1665, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sc-node-comfyui\__init__.py", line 1, in <module>
    from .scnode import NODE_CLASS_MAPPINGS
  File "D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sc-node-comfyui\scnode.py", line 7, in <module>
    import global_table
ModuleNotFoundError: No module named 'global_table'

Cannot import D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sc-node-comfyui module for custom nodes: No module named 'global_table'
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 192 nodes successfully.

        "Success is not just about making money. It's about making a difference." - Unknown


Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiExtremeDetail_v10
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip_text_encoder_a1111.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bsz-auto-hires.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ksampler_gpu.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sampler_rescalecfg.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Textnode.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sampler_tonemap.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ksampler_sdxl.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_model_merging.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImgPrompt
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SimpleMath
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\wildcards.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\facedetailer
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt_generator.py
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_clip_blip_node
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\nui-suite
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Fans
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\failfast-comfyui-extensions-main
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-pants
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
   0.0 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger
   0.0 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly
   0.1 seconds (IMPORT FAILED): D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\sc-node-comfyui
   0.1 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-control
   0.2 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   0.4 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-PromptAttention
   0.5 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.8 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   1.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   1.1 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.1 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   1.1 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   1.3 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.4 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   1.5 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   2.0 seconds: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\com\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready

**Comment by ssitu** [comment]
The error related to this node is the same error being discussed in #15, so once that's fixed you'll be able to load the workflow. Or you can uninstall `ComfyUI-Frame-Interpolation` to get it working and install it back when you need it.

**Comment by Psokratease** [comment]
Thank you so much for your time and for creating programs that constantly make these products better. I look forward to the new release. Have a good day!

**Comment by ssitu** [comment]
This is fixed now.

**Comment by Psokratease** [comment]
Thank you ssitu, it loads up wonderfully now.
