### ISSUE TITLE
Error when using as input to Facial Detailer

### ISSUE THREAD

**Issue by poisenbery** [ssitu/ComfyUI_UltimateSDUpscale#2]
I'm not sure if this is an issue with the Facial Detailer from Impact Pack or if it's an issue with SD Upscale Node, but I only get this error when I use the Ultimate SD Upscale node before the Facial Detailer
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/78466408/2dab2c8d-206d-4e85-9e6f-aa1c86dacfcf)

Reference: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/26

The only way I can get it to work is by converting the image to latent and back to an image

![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/78466408/9b2cfbd2-fef0-4931-8e33-2fff6d9bf501)

The error only occurs when I use this node as an input to the facial detailer.

**Comment by ssitu** [comment]
@poisenbery I believe I fixed it, could you pull the latest commit to see if it fixes it for you?

**Comment by poisenbery** [comment]
@ssitu yes, thank you.
