### ISSUE TITLE
I also don't understand if it's a problem with Ultimate SD Upscale or comfyui.

### ISSUE THREAD

**Issue by suede299** [ssitu/ComfyUI_UltimateSDUpscale#20]
When I open comfyui and process the image for the 1st time, Ultimate SD Upscale is fast (ImgtoImg).
At this point, if I just change some parameters and continue generating, it's still fast.
But if I replace an input image, when I go to Ultimate SD Upscale, there is not enough memory(pretty sure) and the processing becomes slow.
So I did a test, 1. cancel the current queue during processing; 2. start generating again. At this point Ultimate SD Upscale's speed became normal. Even though I canceled the queue before the process reached Ultimate SD Upscale.
The result is that as soon as I replace the input image and then cancel it once during the generation process, then Ultimate SD Upscale is able to process at normal speed.

Translated with www.DeepL.com/Translator

**Comment by ssitu** [comment]
Do you have a small workflow that it happens with? I’ll see if I get the same problem.

**Comment by suede299** [comment]
> Do you have a small workflow that it happens with? I’ll see if I get the same problem.
I found some information at comfyui's issues and finally confirmed that it was a problem with xformers, and now that I switched to PyTorch with nightlyVersion, everything works fine.
