### ISSUE TITLE
Why is the output image size inconsistent with the input image size? I did not set the magnification

### ISSUE THREAD

**Issue by 108863258** [ssitu/ComfyUI_UltimateSDUpscale#21]
Why is the output image size inconsistent with the input image size? I did not set the magnification
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/25278613/6f079d18-60f4-4da8-840c-26bce698e8a3)

**Comment by ssitu** [comment]
The output size will change with the input size and `upscale_by` parameter.

**Comment by ssitu** [comment]
Stale.
