### ISSUE TITLE
Nodes not showing up

### ISSUE THREAD

**Issue by Keller46** [ssitu/ComfyUI_UltimateSDUpscale#23]
So I tried installing via comfyUI manager and git command and the nodes are not showing up and my workflow is saying that it's not installed, I have everything up to date. Can the issue be because I have other extensions? 
this workflow-
![Capybara's_Workflow_v1 4](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/140314445/409aa7b5-3019-4ce1-8287-56bcfbdef082)

![Screenshot 2023-09-29 101207](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/140314445/ebaf4341-6933-4528-9717-7c1413e338c8)
![Screenshot 2023-09-29 101231](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/140314445/442ac2bf-359d-4999-ab53-95a12014149b)

**Comment by ssitu** [comment]
Does the terminal say that it failed to load?

**Comment by bridgesense** [comment]
It seems a recent update to ComfyUI has caused some compatibility issues with this plugin. I encountered a similar problem when trying to load a workspace with this plugin.

I reverted ComfyUI to its August 9th version, which corresponds to the last update of this plugin, and it resolved the issue. The specific commit I reverted to is cf10c5592c2ef91d5f0218a6f0e7a536c02c5d96. It's unclear where the incompatibility arose, but given the substantial changes underway in ComfyUI, it's something to keep an eye on.

**Comment by ssitu** [comment]
I think it might be a custom node causing that problem. I have no problems using this plugin with the current ComfyUI updates.

**Comment by filliptm** [comment]
i ran into this problem with the cu121 portable build for comfy, only works on the 118 it seems X.X

**Comment by ssitu** [comment]
> i ran into this problem with the cu121 portable build for comfy, only works on the 118 it seems X.X

I installed the newest cu121 portable build and USDU is loading up fine. Did you have other custom nodes installed?

**Comment by filliptm** [comment]
> > i ran into this problem with the cu121 portable build for comfy, only works on the 118 it seems X.X
> 
> I installed the newest cu121 portable build and USDU is loading up fine. Did you have other custom nodes installed?

i do indeed, what else would be conflicting with this? i have quite a lot

**Comment by filliptm** [comment]
<img width="1909" alt="image" src="https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/55672949/ee5397f1-2a72-49bc-ab46-b5c873d43993">

it cant seem to find the script, it wasnt in there when i checked, manually downloaded it and put it there, but it seems to still be not loading

**Comment by ssitu** [comment]
> <img alt="image" width="1909" src="https://user-images.githubusercontent.com/55672949/277110605-ee5397f1-2a72-49bc-ab46-b5c873d43993.png">
> it cant seem to find the script, it wasnt in there when i checked, manually downloaded it and put it there, but it seems to still be not loading

It looks like you don't have the original repo installed.
Did you use this command or did you install by downloading the .zip?
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/57548627/fb109e4c-bd7a-4fc0-8c24-e46f5b87e519)

If you downloaded the .zip then you have to get the original repo too, I'll refer you to these instructions:
https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/19#issuecomment-1720219497
