### ISSUE TITLE
Keep getting this error- FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by dfghsderftgerdf** [ssitu/ComfyUI_UltimateSDUpscale#29]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'

**Comment by ssitu** [comment]
Did you use this command to install?
`git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive`
You can delete the folder and try the command again, make sure `--recursive` is used

You can also use the manager extension to install it: https://github.com/ltdrdata/ComfyUI-Manager

If the command doesn't work and you don't want the manager extension then you can follow the instructions here:
https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/19#issuecomment-1720219497

**Comment by dfghsderftgerdf** [comment]
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive
Cloning into 'ComfyUI_UltimateSDUpscale'...
remote: Enumerating objects: 248, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 248 (delta 18), reused 19 (delta 14), pack-reused 213
Receiving objects: 100% (248/248), 64.23 KiB | 131.00 KiB/s, done.
Resolving deltas: 100% (152/152), done.
      0 [main] sh 1834 dofork: child -1 - forked process 9300 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1061549 [main] sh 1834 dofork: child -1 - forked process 6360 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
3139980 [main] sh 1834 dofork: child -1 - forked process 14188 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
7186161 [main] sh 1834 dofork: child -1 - forked process 5048 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
15242626 [main] sh 1834 dofork: child -1 - forked process 11704 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable


Does mean I need to update git?

**Comment by ssitu** [comment]
Yeah sorry, not sure what that git error was. You probably should look it up. Glad it's working now.

> Last one did the trick thanks
