### ISSUE TITLE
import failed   i know this is an old issue but

### ISSUE THREAD

**Issue by jlitz** [ssitu/ComfyUI_UltimateSDUpscale#30]
0.0 seconds (IMPORT FAILED): C:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale

C:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git
Cloning into 'ComfyUI_UltimateSDUpscale'...
remote: Enumerating objects: 248, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (21/21), done.
Receiving objects:  98% (244/248)sed 19 (delta 14), pack-reused 213
Receiving objects: 100% (248/248), 64.23 KiB | 1.15 MiB/s, done.
Resolving deltas: 100% (152/152), done.
 

seems to have installed ok.  Tried a number or times and no luck getting it recognized.  Using it  with Krita and keep getting error.  image below of what was installed 

https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git

**Comment by jlitz** [comment]
maybe  i reinstalled  it   now i   forget which workplace required it  lol

**Comment by jifeng123guo** [comment]
I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you

https://youtu.be/9gIAZYBqbQA

**Comment by maxbizz** [comment]
Thanks @jifeng123guo , This fixed the issue
