### ISSUE TITLE
Using SD1.5 Results in a mess of an upscale?

### ISSUE THREAD

**Issue by jbkrauss** [ssitu/ComfyUI_UltimateSDUpscale#38]
Hello,

I'm trying to create a workflow to compare SD Ultimate Upscale using SDXL alone ; and SD1.5 + a Tile controlnet.
The worklow works fine for SDXL, however using SD1.5 models results in a jumbled mess (even without the controlnet plugged in).
I tried a few different models, a different VAE, but everytime I get the same jumbled result.

Here is a screenshot of my workflow + a typical "jumbled" image + the workflow itself.

What am I doing wrong here? 

![Example](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/43850261/90f89ddc-28f1-4d20-8d96-d0f9bee75f98)
[Jumbled_Images.json](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/files/13588224/Jumbled_Images.json)
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/43850261/386c6fb5-f8ae-457c-9543-8799b2d9fe97)

**Comment by ssitu** [comment]
It might be your prompts, try using a new pair of text encodes for the USDU node and see if that improves things.
