### ISSUE TITLE
previews not working - taesd and latent2RGB

### ISSUE THREAD

**Issue by JarekDerp** [ssitu/ComfyUI_UltimateSDUpscale#42]
Hi,

Am I doing something wrong or it doesn't always work?
I'm starting Comfy with parameter '--preview-method taesd' and have 'Preview method: TAESD (slow)' selected in Comfy Manager.
The Upscaler only shows one image while it's upscaling it and then stops for the rest of the session until I restart Comfy, or change a setting in Comfy Manager.
Is there a way to enable it all the time?
I'm using DirectML and AMD card if that makes any difference.

**Comment by JarekDerp** [comment]
Ok, it works fine if I just keep running the Ultimate SD Upscale over and over, but as soon as I run KSampler once, it stops showing previews. Is this a problem with Comfy or some bug in this node?

**Comment by ssitu** [comment]
The preview on this node should show each tile while they are being made. I don’t think it would be a problem with this node because it is just using ksampler nodes in the background, but I’m not sure.

**Comment by JarekDerp** [comment]
Ok, I found the problem. It's Efficiency nodes that I'm running before the upscale. Looks like there's a bug in their code. They store "global preview method", overwrite it during running their KSampler, and then set it to "none" after the KSampler finishes running...
Thanks anyway and sorry for trouble.
