### ISSUE TITLE
Import Failed (followed instructions)

### ISSUE THREAD

**Issue by ckao10301** [ssitu/ComfyUI_UltimateSDUpscale#43]
Also ran cmd as administrator

C:\Users\ckao1\OneDrive\Desktop\fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive
Cloning into 'ComfyUI_UltimateSDUpscale'...
remote: Enumerating objects: 256, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (26/26), done.
Receiving objects: 100% (256/256), 68.88 KiB | 839.00 KiB/s, done.3

Resolving deltas: 100% (155/155), done.
Submodule 'repositories/ultimate_sd_upscale' (https://github.com/Coyote-A/ultimate-upscale-for-automatic1111) registered for path 'repositories/ultimate_sd_upscale'
Cloning into 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale'...
remote: Enumerating objects: 318, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 318 (delta 38), reused 81 (delta 29), pack-reused 225
Receiving objects: 100% (318/318), 32.23 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (113/113), done.
fatal: cannot write keep file 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/.git/modules/repositories/ultimate_sd_upscale/objects/pack/pack-54b1f258e441ccf82bf2612e0f853c5e3da1ec4e.keep': Filename too long
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/Coyote-A/ultimate-upscale-for-automatic1111' into submodule path 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale' failed
Failed to clone 'repositories/ultimate_sd_upscale'. Retry scheduled
Cloning into 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale'...
remote: Enumerating objects: 318, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 318 (delta 38), reused 81 (delta 29), pack-reused 225
Receiving objects: 100% (318/318), 32.23 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (113/113), done.
fatal: cannot write keep file 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/.git/modules/repositories/ultimate_sd_upscale/objects/pack/pack-ed1ce62df038b132b4e535c5b90b33d217fb620d.keep': Filename too long
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/Coyote-A/ultimate-upscale-for-automatic1111' into submodule path 'C:/Users/ckao1/OneDrive/Desktop/fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale/repositories/ultimate_sd_upscale' failed
Failed to clone 'repositories/ultimate_sd_upscale' a second time, aborting

**Comment by microvswind** [comment]
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/103630540/dc716e93-e92e-4c15-8472-58b6821e2826)
** ComfyUI startup time: 2024-01-10 09:51:00.580139
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /opt/conda/bin/python
** Log path: /mnt/workspace/ComfyUI/comfyui.log

**Comment by danikhani** [comment]
Your path is too long: `C:\Users\ckao1\OneDrive\Desktop\fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes`

Just go to another folder like in c:\users\ckao1 and then do `git clone https://github.com/ssitu/ComfyUI_UltimateSDUpscale --recursive`. 

After that cut the folder and paste it under `C:\Users\ckao1\OneDrive\Desktop\fresh_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes`

That solved my problem

**Comment by jifeng123guo** [comment]
I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you

https://youtu.be/9gIAZYBqbQA

**Comment by AlexJung3** [comment]
> I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you
> 
> https://youtu.be/mrKGCd1QuyA

Well done, fix my problem too.

**Comment by Dimava2** [comment]
> I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you
> 
> https://youtu.be/mrKGCd1QuyA

So what was that?
