### ISSUE TITLE
fail when installing

### ISSUE THREAD

**Issue by omvyy** [ssitu/ComfyUI_UltimateSDUpscale#46]
When I'm installing there is this issue:
![Zrzut ekranu 2024-01-11 200848](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/156361439/fe4643ca-ce45-45e3-bdad-df16d131ace1)

**Comment by ssitu** [comment]
You'll need to install git to use that command. If you don't want to install git, you may follow these instructions found here: https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/19#issuecomment-1720219497

**Comment by jifeng123guo** [comment]
I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you

https://youtu.be/9gIAZYBqbQA
