### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by 657233220** [ssitu/ComfyUI_UltimateSDUpscale#49]
#46 
![screenshot-1705407588606](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/156797058/c8339a33-3b56-4812-968a-6b3ffebef306)

**Comment by will584520** [comment]
me too

**Comment by bealj89** [comment]
I have the same thing going on

**Comment by bealj89** [comment]
I have tried to reinstall and no luck

**Comment by bealj89** [comment]
I am getting this error
![Capture1](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/156993938/6373b634-c938-4c57-bdcc-bccda7cb963d)
![Capture](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/156993938/c74eb051-3b6b-4b99-b140-4e15ab5256a8)

**Comment by ssitu** [comment]
What does the terminal say when you start comfy?

**Comment by bealj89** [comment]
It is the error that I provided second. When loading the graph the follong node types were not found

**Comment by danikhani** [comment]
Make a screenshot from your terminal (this screen: ![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/30578398/0ee5afe0-6f4d-42d0-a229-572d2f6f8b78)) after you tried to install the extension.

**Comment by jifeng123guo** [comment]
I also encountered this problem and tried many methods and finally solved it. I recorded a video with the solution, I hope it can help you

https://youtu.be/9gIAZYBqbQA

**Comment by bealj89** [comment]
C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-01-22 20:28:55.522190
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\comfyui.log
[ComfyUI-Manager] Windows event loop policy mode enabled

Prestartup times for custom nodes:
   0.1 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12281 MB, total RAM 32706 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.2.1)
### ComfyUI Revision: 1917 [d76a04b6] | Released on '2024-01-17'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'

Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale\\repositories\\ultimate_sd_upscale\\scripts\\ultimate-upscale.py'
Traceback (most recent call last):
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale-main\\__init__.py'

Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_UltimateSDUpscale-main\\__init__.py'
Traceback (most recent call last):
  File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ultimate-upscale-for-automatic1111\\__init__.py'

Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111 module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\Bealj\\OneDrive\\Documents\\AI\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ultimate-upscale-for-automatic1111\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111
   0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main
   0.0 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.5 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by NiklausM9** [comment]
I had the same issue, solved after I uninstalled Reactor node

**Comment by jifeng123guo** [comment]
*you can try this method*
https://youtu.be/9gIAZYBqbQA

NiklausM9 ***@***.***> 于2024年1月29日周一 09:10写道：

**Comment by GOATGAMER07** [comment]
no error, everything is good , only thing they messed up is location placing in code

solution below:

put ultimate-upscale.py in exact location which i provided location below
   
".....\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py"




> C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build ** ComfyUI startup time: 2024-01-22 20:28:55.522190 ** Platform: Windows ** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct 2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] ** Python executable: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\python_embeded\python.exe ** Log path: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\comfyui.log [ComfyUI-Manager] Windows event loop policy mode enabled
> 
> Prestartup times for custom nodes: 0.1 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 12281 MB, total RAM 32706 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync VAE dtype: torch.bfloat16 Using pytorch cross attention
> 
> ### Loading: ComfyUI-Manager (V2.2.1)
> ### ComfyUI Revision: 1917 [d76a04b6] | Released on '2024-01-17'
> FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json Traceback (most recent call last): File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale__init__.py", line 24, in from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in from usdu_patch import usdu File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in from repositories import ultimate_upscale as usdu File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories__init__.py", line 14, in spec.loader.exec_module(ultimate_upscale) File "", line 936, in exec_module File "", line 1073, in get_code File "", line 1130, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py'
> 
> Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py' Traceback (most recent call last): File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 936, in exec_module File "", line 1073, in get_code File "", line 1130, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main\**init**.py'
> 
> Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main\**init**.py' Traceback (most recent call last): File "C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 936, in exec_module File "", line 1073, in get_code File "", line 1130, in get_data FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111\**init**.py'
> 
> Cannot import C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111 module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111\**init**.py'
> 
> Import times for custom nodes: 0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ultimate-upscale-for-automatic1111 0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale-main 0.0 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus 0.0 seconds (IMPORT FAILED): C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale 0.5 seconds: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188 [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json FETCH DATA from: C:\Users\Bealj\OneDrive\Documents\AI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (2)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

no error, everything is good , only thing they messed up is location placing in code

solution below:

put ultimate-upscale.py in exact location which i provided location below
   
".....\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py"

**Comment by GOATGAMER07** [comment]
> #46 ![screenshot-1705407588606](https://private-user-images.githubusercontent.com/156797058/297043068-c8339a33-3b56-4812-968a-6b3ffebef306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzU2MzksIm5iZiI6MTcwNjc3NTMzOSwicGF0aCI6Ii8xNTY3OTcwNTgvMjk3MDQzMDY4LWM4MzM5YTMzLTNiNTYtNDgxMi05NjhhLTZiM2ZmZWJlZjMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwODE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDQ3NjU4YzFmZWEyMzFjNTMwNDE4YTVkMDdmMjg5ZGMwNGQxZDg5ZjBmZTYxOGVlNWFhYTBkYzM5YmYxMDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ie6cJowN2DHf67s2M2INOVa9pp85IBE_-vz-u86WGXc)

no error, everything is good , only thing they messed up is location placing in code

solution below:

put ultimate-upscale.py in exact location which i provided location below
   
".....\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py"

**Comment by GOATGAMER07** [comment]
issue closee 👍

**Comment by GOATGAMER07** [comment]
> me too

no error, everything is good , only thing they messed up is location placing in code

solution below:

put ultimate-upscale.py in exact location which i provided location below
   
".....\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py"

**Comment by GOATGAMER07** [comment]
close the issue ![Uploading AnimeCloseGIF (2).gif…]()
