### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by Dimaray** [ssitu/ComfyUI_UltimateSDUpscale#59]
Yesterday everything was working and today USDU stopped working. There was an update in python and some nodes not sure what caused this. 
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/155167594/525bc7d1-d5fc-498c-b0b9-0ffc60e8dbf5)
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/155167594/11aa4363-8edd-468a-a500-99d54e34298b)

**Comment by Dimaray** [comment]
maybe need to reinstall the whole thing...

got prompt
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "D:\#AI\ComfyUI\server.py", line 637, in trigger_on_prompt
    json_data = handler(json_data)
                ^^^^^^^^^^^^^^^^^^
  File "D:\#AI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 861, in prompt_handler
    if node["class_type"] == "smZ CLIPTextEncode":
       ~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'
Error handling request
Traceback (most recent call last):
  File "D:\#AI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\#AI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\#AI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\#AI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\#AI\ComfyUI\server.py", line 476, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\#AI\ComfyUI\execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

**Comment by Dimaray** [comment]
I might have found the problem. Testing

**Comment by Dimaray** [comment]
Issue found: comfyui-reactor-node - https://github.com/Gourieff/comfyui-reactor-node
Not sure but this is fucking with the Upscaler

**Comment by ssitu** [comment]
Yeah this issue popped up recently. The developer of that node uses my system for porting over extensions from a1111, so I think they changed something in there recently to cause the conflict, but I'm not sure. I don't think this conflict existed before.

**Comment by Dimaray** [comment]
Before it was ok.

**Comment by s-damyanov** [comment]
The fix from here worked out for me: https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/53
