### ISSUE TITLE
Image isn't sampling with "Ultimate SD Upscale (No upscale)" if mode_type = None

### ISSUE THREAD

**Issue by fractal-fumbler** [ssitu/ComfyUI_UltimateSDUpscale#6]
hello :) 
been using your nodes so far and getting very nice result.
encountered with particular situation:
comfyUI version is @https://github.com/comfyanonymous/ComfyUI/commit/6fb084f39de495ca2cdfd482720069378d6e68ae
workflow includes 
* Ksampler (default or advanced one)
* VAE Decode
* "Ultimate SD Upscale (No upscale)"
![image](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/80472908/6e81bbe0-c2fa-425c-8bfc-f1263db35b4a)

1. If mode_type is set to **Linear** or **Chess** sampling is happening with steps, cfg and scheduler set in node

2. If mode_type is set to **None** images aren't using node settings (steps, cfg and scheduler), but instead just producing same pictures that was generated in Ksampler node

there is no actual error in console
```python
got prompt
Canva size: 1024x1024
Image size: 1024x1024
Scale factor: 1
Tile size: 1024x1024
Tiles amount: 1
Grid: 1x1
Redraw enabled: False
Seams fix mode: NONE
Prompt executed in 0.59 seconds
got prompt
Canva size: 1024x1024
Image size: 1024x1024
Scale factor: 1
Tile size: 1024x1024
Tiles amount: 1
Grid: 1x1
Redraw enabled: False
Seams fix mode: NONE
Prompt executed in 0.64 seconds
```

is it an error?

**Comment by ssitu** [comment]
Mode type must not be None for sampling to happen. For the No Upscale node, it  upscales the image by a factor of 1, so nothing happens to the image. Since the image isn’t being upscaled and sampling doesn’t happen, then the image will be unchanged.

**Comment by fractal-fumbler** [comment]
thanks for explanation :)
