### ISSUE TITLE
Error after updating ComfyUI

### ISSUE THREAD

**Issue by gonzalu** [ssitu/ComfyUI_UltimateSDUpscale#62]
Node is failing to load today after updating ComfyUI and some modules:

```
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (E:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (E:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
```

Tried re-installing but still fails to load. 

Thank you

**Comment by gonzalu** [comment]
Seems that installing "reactor" breaks USDU :( 

It is working after uninstalling Reactor

https://github.com/Gourieff/comfyui-reactor-node

**Comment by ssitu** [comment]
I am aware of this conflict. Surprisingly, I can load both without problems. What Python version are you using with ComfyUI?

**Comment by gonzalu** [comment]
If it helps, here is the startup info

```
E:\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-03-03 20:22:50.417324
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: E:\ComfyUI\python_embeded\python.exe
** Log path: E:\ComfyUI\comfyui.log
[Maras IT] Initialization

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MarasIT-Nodes
   0.1 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 65478 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
```

**Comment by BigUncle** [comment]
It is likely that this project did not update the submodule: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111

You can try my project, https://github.com/BigUncle/ComfyUI_UltimateSDUpscale ,to see if it can be solved.

Or you enter this `custom_nodes/ComfyUI_UltimateSDUpscale directory in the command line, and then run `git submodule update --init --recursive`

**Comment by 6sixteen** [comment]
My Python version is 3.11.
And the promblem is
`
from modules import processing, shared, images, devices, scripts
# the modules is still from reactor modules 
from modules.processing import StableDiffusionProcessing
from modules.processing import Processed
from modules.shared import opts, state
from enum import Enum
`
And these code may not make sense
`
for module in modules_used:
    if module in sys.modules:
        original_imported_modules[module] = sys.modules.pop(module)
`
Maybe just change 'modules'

**Comment by mashiye** [comment]
the same issue

**Comment by Sarimae** [comment]
Same issue:
File "E:\ComfyUI\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (E:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (E:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
E:\ComfyUI\python_embeded\Lib\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.

**Comment by ssitu** [comment]
Does this still happen?

**Comment by Jobias** [comment]
You guys I just did a fresh install of everything and found the same issue, did some test, and found that, for me, the issue is there when I try to use a ControlNet++ node, using the Pro Max Model, and the normal type. I'll try to do more tests around it, but hope that info is usefull for anybody

**Comment by nadainterior** [comment]
> You guys I just did a fresh install of everything and found the same issue, did some test, and found that, for me, the issue is there when I try to use a ControlNet++ node, using the Pro Max Model, and the normal type. I'll try to do more tests around it, but hope that info is usefull for anybody

did find any solution i am stack in the same error
