### ISSUE TITLE
Ultimate Upscale not resampling?  Redraw enabled: False ???

### ISSUE THREAD

**Issue by EricRollei** [ssitu/ComfyUI_UltimateSDUpscale#66]
I noticed in the last week that Ultimate Upscale sometimes just doesn't resample and only uses the upscale model and I can't figure out why.   If I restart ComfyUI then it will work normally for a while but then gets out of whack.    When it's not working correctly,  I get the following message in the console:
Canva size: 3456x2688
Image size: 1152x896
Scale factor: 3
Upscaling iteration 1 with scale factor 3
Tile size: 1152x896
Tiles amount: 9
Grid: 3x3
**Redraw enabled: False**
Seams fix mode: NONE

And after I restart ComfyUI, using exactly the same settings it runs and this is the console output.
Canva size: 3456x2688
Image size: 1152x896
Scale factor: 3
Upscaling iteration 1 with scale factor 3
Tile size: 1152x896
Tiles amount: 9
Grid: 3x3
**Redraw enabled: True**
Seams fix mode: NONE
Requested to load AutoencoderKL
Loading 1 new model
Requested to load SDXL
Requested to load ControlNet
Requested to load ControlNet
Loading 3 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.22it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:14<00:00,  3.40it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.34it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:08<00:00,  5.54it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.44it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.07it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.35it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:09<00:00,  5.11it/s]
Requested to load ControlNet
Requested to load ControlNet
Loading 2 new models
100%|██████████████████

**Comment by ssitu** [comment]
Is this still happening?

**Comment by EricRollei** [comment]
I haven't seen the error after the last updates thank you.  I'll close this now.
