### ISSUE TITLE
1 bug need fix,please help

### ISSUE THREAD

**Issue by T8mars** [ssitu/ComfyUI_UltimateSDUpscale#68]
the node conflict with node:[ComfyUI-BiRefNet](https://github.com/viperyl/ComfyUI-BiRefNet)
![a1](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/96167788/7924b3bd-a33f-4f27-ad3e-ce39ed8831e5)
![a2](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/96167788/3ff49b97-61a5-4dca-8339-c1b698847115)

**Comment by ssitu** [comment]
Some of your error is cut off, could I see a larger screenshot?

**Comment by T8mars** [comment]
it has been solved ,thanks
