### ISSUE TITLE
Feature request: support custom sampler 

### ISSUE THREAD

**Issue by frankyifei** [ssitu/ComfyUI_UltimateSDUpscale#76]
New sampler and schedulers emerging quickly, is it possible to make ultimateSDUpscale support these new techniques, such as TCD sampler, AlignYourSteps schedulers, restart scheduler and others.

**Comment by ssitu** [comment]
So you want a node input for custom sampler nodes?

**Comment by frankyifei** [comment]
yes, it would be great if it can use custom sampler. I understand it is current using common_sampler, is it going to be lots of work supporting this?

**Comment by ssitu** [comment]
Probably not, I'll see what I can do

**Comment by ethanfel** [comment]
> Probably not, I'll see what I can do

hey, if possible could you do the same for the scheduler (sigmas ?) AlignYourSteps isn't usable atm with ultimate upscale. This scheduler would be super useful with it.

**Comment by ssitu** [comment]
So just add inputs for a custom sampler and custom sigmas? And which approach is more preferable: adding them as optional inputs vs making new nodes for them?

**Comment by ethanfel** [comment]
> So just add inputs for a custom sampler and custom sigmas? And which approach is more preferable: adding them as optional inputs vs making new nodes for them?

I believe both ways work. I would probably choose a new node myself. Following Comfyui arrangement with the regular ksampler without the inputs and the 2 samplercustoms with inputs.

**Comment by tilktilk5** [comment]
ive been yearning for this feature since custom schedulers became a thing. i would love a "sigmas" input.

**Comment by gobshyte** [comment]
Oh yeah I was just looking to see if I could use AYS scheduler with this, so yes please!

**Comment by ssitu** [comment]
Alright, a new node has been added for this. Let me know if there are any issues/suggestions with the new one or any bugs that may have appeared with the old nodes.

**Comment by gobshyte** [comment]
Excellent, but...  can I use this new node in place of SD Upscale (No Upscale) ?
A the moment I am testing with an upscaler connected but with upscale set to 1.0 instead, and hoping that mimics the behjaviour of the No Upscale node but alowing custom sampler/sigmas

**Comment by ssitu** [comment]
I think I'll make the upscale model optional, so it will skip the upscale if it's not provided.

**Comment by gobshyte** [comment]
Cool :)

**Comment by ethanfel** [comment]
> I think I'll make the upscale model optional, so it will skip the upscale if it's not provided.

thanks for the update, it's great
