### ISSUE TITLE
Error when using ComfyUI extension for stable-diffusion-webui

### ISSUE THREAD

**Issue by Deividaszu** [ssitu/ComfyUI_UltimateSDUpscale#8]
When I am trying your example I am getting this error message, maybe you know why this is happening? 

![456e544c8ff00513f46648504a03758c](https://github.com/ssitu/ComfyUI_UltimateSDUpscale/assets/30309884/83c3d54a-eb3e-4e29-947d-5c0e92810857)

**Comment by ssitu** [comment]
Are you running comfyui within the a1111 web ui?
