### ISSUE TITLE
Can we use Tensorrt model?

### ISSUE THREAD

**Issue by hahajaja** [ssitu/ComfyUI_UltimateSDUpscale#88]
Reference: https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt

**Comment by cgrossi** [comment]
I believe you could solve this by using the regular tensorrt upscale nodes to upscale the images using the tensorrt model and then feeding those images into the ultimatesdupscale (no upscale) node that comes with the node pack and run the upscale as you normally would
